[build]
  command = "npm install --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_OPTIONAL = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
